### ISSUE TITLE
ValueError: Cannot feed value of shape (30, 32, 32, 3) for Tensor 'ExpandDims:0', which has shape '(1, ?, ?, 3)'

### ISSUE THREAD

**Issue by IPNUISTlegal** [nnUyi/Inception-Score#3]
同学，我用的python3 ，用你数据集。会报错，谷歌找不合适的解决办法。不知道你有没有好的解决办法？谢谢
PS：IS程序改了两处处，你上传的没有改   https://github.com/openai/improved-gan/blob/0b7ed92e47ff7047701be3e10a3bd6363999f5e7/inception_score/model.py#L92

https://github.com/openai/improved-gan/blob/0b7ed92e47ff7047701be3e10a3bd6363999f5e7/inception_score/model.py#L90

**Comment by nnUyi** [comment]
把里面的txt文件去掉哈

**Comment by IPNUISTlegal** [comment]
打扰了，还是报同样的错误。
https://github.com/openai/improved-gan/issues/32
TensorFlow版本问题。谢谢了

**Comment by Shan2L** [comment]
和楼上遇到了相同的问题，希望楼主能帮忙解决下
ValueError: Cannot feed value of shape (30, 32, 32, 3) for Tensor 'ExpandDims:0', which has shape '(1, ?, ?, 3)'
